# Load local syslog module
module(load="imuxsock")

# Listen on UDP 514
module(load="imudp")
input(type="imudp" port="514")

# Forward everything to SIEM via UDP
*.* @10.10.30.10:514
*.* @10.10.30.15:1514
