# Load modules
module(load="imuxsock")
module(load="imfile" PollingInterval="2")

# Set default permissions
$FileOwner root
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser root
$PrivDropToGroup root
$WorkDirectory /var/spool/rsyslog

# Input from Pi-hole DNS log
input(type="imfile"
      File="/var/log/pihole/pihole.log"
      Tag="pihole"
      Severity="info"
      Facility="local0")

# Forward all logs directly to Wazuh
*.* @10.10.30.10:514

# Forward all logs directly to Splunk
*.* @10.10.30.15:1514
